name: CI/CD Pipeline - E Mart App

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        python-version: ['3.10', '3.11']
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ matrix.python-version }}-${{ hashFiles('**/pyproject.toml') }}
        restore-keys: |
          ${{ runner.os }}-pip-${{ matrix.python-version }}-
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install frappe-bench
        pip install ruff bandit pytest
    
    - name: Run linting
      run: |
        python -m ruff check e_mart/ --output-format=github
    
    - name: Run security checks
      run: |
        bandit -r e_mart/ -f json -o bandit-report.json || true
    
    - name: Run tests
      run: |
        python e_mart/run_tests.py
    
    - name: Check syntax
      run: |
        python -m py_compile e_mart/__init__.py
        python -m py_compile e_mart/hooks.py
        python -m py_compile e_mart/setup.py
    
    - name: Upload test results
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: test-results-${{ matrix.python-version }}
        path: |
          bandit-report.json
          *.log

  security:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Run security scan
      uses: github/codeql-action/init@v2
      with:
        languages: python
    
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v2

  documentation:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Check documentation
      run: |
        # Check if README exists
        test -f README.md || exit 1
        
        # Check if installation guide exists
        test -f e_mart/INSTALLATION.md || exit 1
        
        # Check if GitHub setup guide exists
        test -f GITHUB_SETUP.md || exit 1
        
        echo "✅ All documentation files present"
    
    - name: Validate markdown
      run: |
        # Basic markdown validation
        grep -q "# " README.md || exit 1
        grep -q "## " e_mart/INSTALLATION.md || exit 1
        echo "✅ Markdown structure is valid"

  build:
    runs-on: ubuntu-latest
    needs: [test, security, documentation]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Build package
      run: |
        python -m pip install build
        python -m build
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: e-mart-app
        path: dist/

  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Create release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ github.run_number }}
        release_name: E Mart App v${{ github.run_number }}
        body: |
          ## What's Changed
          - Automated build and test pipeline
          - Enhanced security features
          - Performance optimizations
          - Mobile app support
          - API integration capabilities
          
          ## Installation
          ```bash
          bench get-app e_mart https://github.com/${{ github.repository }}
          bench install-app e_mart
          ```
        draft: false
        prerelease: false 